export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
export const UPDATE_CURRENT_SEARCH = 'UPDATE_CURRENT_SEARCH';
export const UPDATE_CURRENT_TRACK_ID = 'UPDATE_SEARCH_TRACK_ID';
export const UPDATE_FUTURED_PLAYLIST = 'UPDATE_FUTURED_PLAYLIST';